on:
  # Replace with your desired trigger, e.g. push to main branch
  push:
    branches: [ master, setup_ci ]

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create archive
        run: |
          cd RNAseq/Workflow_Documentation  # Replace with the path to your folder
          ls -l 
          echo "PKG_DIR=$(realpath NF_RCP*)" >> $GITHUB_ENV
          echo "## Setting PKG_DIR context: $PKG_DIR"

      - name: zip package
        run: |
            zip -r $(basename $PKG_DIR).zip $PKG_DIR
            echo PKG_FULLPATH=$(realpath $(basename $PKG_DIR).zip) >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: $PKG_DIR  # Replace with your desired artifact name
          path: $PKG_DIR.zip
          if-no-files-found: error # fail if archive isn't uploaded for any reason
